param(
    [Parameter(Mandatory = $true)]
    [string]$FrontendApiUrl,
    [Parameter(Mandatory = $true)]
    [string]$AiBaseUrl,
    [Parameter(Mandatory = $true)]
    [string]$FrontendOrigin,
    [string]$DbHost = "",
    [int]$DbPort = 5432,
    [string]$DbName = "",
    [string]$DbUser = "",
    [string]$DbPassword = "",
    [string]$JwtSigningKey = "",
    [string]$SharedApiKey = "",
    [switch]$SkipDatabase,
    [switch]$GenerateSecrets
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

function Normalize-Url {
    param([string]$value)
    $result = $value.Trim().TrimEnd("/")
    if ([string]::IsNullOrWhiteSpace($result)) {
        throw "URL invalida."
    }
    return $result
}

function New-SecureRandom {
    param([int]$length = 48)
    $bytes = New-Object byte[] $length
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    return [Convert]::ToBase64String($bytes).Substring(0, $length)
}

function Assert-DatabaseArgs {
    if ($SkipDatabase) {
        return
    }
    if (
        [string]::IsNullOrWhiteSpace($DbHost) -or
        [string]::IsNullOrWhiteSpace($DbName) -or
        [string]::IsNullOrWhiteSpace($DbUser) -or
        [string]::IsNullOrWhiteSpace($DbPassword)
    ) {
        throw "Faltan parametros de DB. Define DbHost/DbName/DbUser/DbPassword o usa -SkipDatabase."
    }
}

function Set-FrontendRuntimeConfig {
    param([string]$apiUrl)
    $configPath = Join-Path $root "frontend-angular\web\public\app-config.js"
    @"
window.__APP_CONFIG__ = {
  apiUrl: '$apiUrl'
};
"@ | Set-Content -Path $configPath -Encoding UTF8
    Write-Host "[OK] Updated $configPath" -ForegroundColor Green
}

function Set-BackendProductionConfig {
    param(
        [string]$aiUrl,
        [string]$origin,
        [string]$connectionString,
        [string]$jwtKey,
        [string]$apiKey,
        [bool]$updateDb
    )
    $path = Join-Path $root "backend-dotnet\src\Api\appsettings.Production.json"
    if (-not (Test-Path $path)) {
        throw "No existe $path"
    }

    $json = Get-Content -Path $path -Raw | ConvertFrom-Json
    $json.Database.Provider = "Postgres"
    if ($updateDb) {
        $json.ConnectionStrings.Default = $connectionString
    }
    $json.PythonAi.BaseUrl = $aiUrl
    if ($apiKey) {
        $json.PythonAi.ApiKey = $apiKey
    }
    $json.Cors.AllowedOrigins = @($origin)
    if ($jwtKey) {
        $json.Jwt.SigningKey = $jwtKey
    }

    $updated = $json | ConvertTo-Json -Depth 20
    Set-Content -Path $path -Value $updated -Encoding UTF8
    Write-Host "[OK] Updated $path" -ForegroundColor Green
}

function Write-EnvFile {
    param(
        [string]$connectionString,
        [string]$jwtKey,
        [string]$apiKey,
        [string]$aiUrl,
        [string]$frontendOriginVal
    )
    $envPath = Join-Path $root ".env"
    @"
# Auto-generated by set-production-config.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')
APP_ENV=production
ASPNETCORE_ENVIRONMENT=Production
ConnectionStrings__Default=$connectionString
Jwt__SigningKey=$jwtKey
PythonAi__BaseUrl=$aiUrl
PythonAi__ApiKey=$apiKey
API_KEY=$apiKey
Cors__AllowedOrigins__0=$frontendOriginVal
Storage__RetentionDays=365
Storage__CleanupIntervalMinutes=43200
RefreshTokens__StoragePath=storage/refresh_tokens.json
RefreshTokens__CleanupIntervalMinutes=10080
"@ | Set-Content -Path $envPath -Encoding UTF8
    Write-Host "[OK] Updated $envPath" -ForegroundColor Green
}

function Test-ProductionPreflight {
    Write-Host "`n--- Preflight checks ---" -ForegroundColor Cyan
    $issues = @()

    # Check .env doesn't have CHANGE_ME
    $envPath = Join-Path $root ".env"
    if (Test-Path $envPath) {
        $content = Get-Content -Path $envPath -Raw
        if ($content -match "CHANGE_ME") {
            $issues += "[WARN] .env still contains CHANGE_ME placeholders"
        }
    }

    # Check appsettings.Production.json
    $prodSettings = Join-Path $root "backend-dotnet\src\Api\appsettings.Production.json"
    if (Test-Path $prodSettings) {
        $json = Get-Content -Path $prodSettings -Raw | ConvertFrom-Json
        if ($json.ConnectionStrings.Default -match "CHANGE_ME|\$\{") {
            $issues += "[WARN] appsettings.Production.json DB connection not configured"
        }
        if ($json.Jwt.SigningKey -match "CHANGE_ME|\$\{") {
            $issues += "[WARN] appsettings.Production.json JWT key not configured"
        }
        if ($json.Cors.AllowedOrigins -contains "http://localhost:4200") {
            $issues += "[WARN] CORS still allows localhost:4200"
        }
    }

    # Check frontend config
    $frontConfig = Join-Path $root "frontend-angular\web\public\app-config.js"
    if (Test-Path $frontConfig) {
        $content = Get-Content -Path $frontConfig -Raw
        if ($content -match "localhost") {
            $issues += "[WARN] Frontend app-config.js still points to localhost"
        }
    }

    if ($issues.Count -eq 0) {
        Write-Host "[PASS] All preflight checks passed" -ForegroundColor Green
    } else {
        foreach ($issue in $issues) {
            Write-Host $issue -ForegroundColor Yellow
        }
    }
    return $issues.Count -eq 0
}

$frontendApi = Normalize-Url -value $FrontendApiUrl
$aiBase = Normalize-Url -value $AiBaseUrl
$origin = Normalize-Url -value $FrontendOrigin

Assert-DatabaseArgs
$updateDb = -not $SkipDatabase
$connection = if ($updateDb) {
    "Host=$DbHost;Port=$DbPort;Database=$DbName;Username=$DbUser;Password=$DbPassword"
} else {
    ""
}

# Generate secrets if requested or not provided
if ($GenerateSecrets -or [string]::IsNullOrWhiteSpace($JwtSigningKey)) {
    $JwtSigningKey = New-SecureRandom -length 48
    Write-Host "[OK] Generated JWT signing key" -ForegroundColor Green
}
if ($GenerateSecrets -or [string]::IsNullOrWhiteSpace($SharedApiKey)) {
    $SharedApiKey = New-SecureRandom -length 32
    Write-Host "[OK] Generated shared API key" -ForegroundColor Green
}

Set-FrontendRuntimeConfig -apiUrl $frontendApi
Set-BackendProductionConfig -aiUrl $aiBase -origin $origin -connectionString $connection -jwtKey $JwtSigningKey -apiKey $SharedApiKey -updateDb $updateDb
Write-EnvFile -connectionString $connection -jwtKey $JwtSigningKey -apiKey $SharedApiKey -aiUrl $aiBase -frontendOriginVal $origin

Write-Host ""
if ($updateDb) {
    Write-Host "Production config ready." -ForegroundColor Green
} else {
    Write-Host "Production config ready (DB pendiente)." -ForegroundColor Yellow
}

Test-ProductionPreflight | Out-Null